spring:
  application:
    name: MDTManager
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB
  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
      
server:
   host: 129.254.91.134
   port: 12985
   error:
      include-message: always

logging:
   level:
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-40.40logger{39} | %msg%n"



rootDir: ${MDT_HOME}

instanceManager:
  type: jar
  homeDir: ${rootDir}/mdt-manager
  bundlesDir: ${rootDir}/bundles
  defaultMDTInstanceJarFile: ${instanceManager.homeDir}/faaast-starter-all.jar
  repositoryEndpointFormat: https://${server.host}:%d/api/v3.0

jpa:
  jdbc:
    url: jdbc:h2:${instanceManager.homeDir}/descriptors
    user: sa
    password: ""
  properties:
    hibernate.show_sql: false
    hibernate.format_sql: false
    hibernate.hbm2ddl.auto: update
     
#mqtt:
#  clientId: MDTInstanceManager
#  endpoint: tcp://localhost:1883
   
executor:
  workspaceDir: ${instanceManager.instancesDir}
  sampleInterval: 2s
  startTimeout: 1m
  startConcurrency: 3
  defaultMDTInstanceJarFile: ${executor.workspaceDir}/faaast-starter-all.jar
  heapSize: 256m
      
docker:
  dockerEndpoint: http://${server.host}:2375
  imageName: faaast-starter
